// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class EmcureUser extends administration.proxies.Account
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.EmcureUser";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FirstName("FirstName"),
		LastName("LastName"),
		MobileNo("MobileNo"),
		Mailid("Mailid"),
		EmployeeID("EmployeeID"),
		Address("Address"),
		Designation("Designation"),
		Status("Status"),
		FullName("FullName"),
		Email("Email"),
		IsLocalUser("IsLocalUser"),
		Name("Name"),
		Password("Password"),
		LastLogin("LastLogin"),
		Blocked("Blocked"),
		BlockedSince("BlockedSince"),
		Active("Active"),
		FailedLogins("FailedLogins"),
		WebServiceUser("WebServiceUser"),
		IsAnonymous("IsAnonymous"),
		UserRoles("System.UserRoles"),
		User_Language("System.User_Language"),
		User_TimeZone("System.User_TimeZone");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EmcureUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EmcureUser(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject emcureUserMendixObject)
	{
		super(context, emcureUserMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, emcureUserMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.EmcureUser initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.EmcureUser(context, mendixObject);
	}

	public static myfirstmodule.proxies.EmcureUser load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.EmcureUser.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.EmcureUser> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.EmcureUser.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName()
	{
		return getFirstName(getContext());
	}

	/**
	 * @param context
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FirstName.toString());
	}

	/**
	 * Set value of FirstName
	 * @param firstname
	 */
	public final void setFirstName(java.lang.String firstname)
	{
		setFirstName(getContext(), firstname);
	}

	/**
	 * Set value of FirstName
	 * @param context
	 * @param firstname
	 */
	public final void setFirstName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String firstname)
	{
		getMendixObject().setValue(context, MemberNames.FirstName.toString(), firstname);
	}

	/**
	 * @return value of LastName
	 */
	public final java.lang.String getLastName()
	{
		return getLastName(getContext());
	}

	/**
	 * @param context
	 * @return value of LastName
	 */
	public final java.lang.String getLastName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LastName.toString());
	}

	/**
	 * Set value of LastName
	 * @param lastname
	 */
	public final void setLastName(java.lang.String lastname)
	{
		setLastName(getContext(), lastname);
	}

	/**
	 * Set value of LastName
	 * @param context
	 * @param lastname
	 */
	public final void setLastName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lastname)
	{
		getMendixObject().setValue(context, MemberNames.LastName.toString(), lastname);
	}

	/**
	 * @return value of MobileNo
	 */
	public final java.lang.String getMobileNo()
	{
		return getMobileNo(getContext());
	}

	/**
	 * @param context
	 * @return value of MobileNo
	 */
	public final java.lang.String getMobileNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MobileNo.toString());
	}

	/**
	 * Set value of MobileNo
	 * @param mobileno
	 */
	public final void setMobileNo(java.lang.String mobileno)
	{
		setMobileNo(getContext(), mobileno);
	}

	/**
	 * Set value of MobileNo
	 * @param context
	 * @param mobileno
	 */
	public final void setMobileNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mobileno)
	{
		getMendixObject().setValue(context, MemberNames.MobileNo.toString(), mobileno);
	}

	/**
	 * @return value of Mailid
	 */
	public final java.lang.String getMailid()
	{
		return getMailid(getContext());
	}

	/**
	 * @param context
	 * @return value of Mailid
	 */
	public final java.lang.String getMailid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Mailid.toString());
	}

	/**
	 * Set value of Mailid
	 * @param mailid
	 */
	public final void setMailid(java.lang.String mailid)
	{
		setMailid(getContext(), mailid);
	}

	/**
	 * Set value of Mailid
	 * @param context
	 * @param mailid
	 */
	public final void setMailid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mailid)
	{
		getMendixObject().setValue(context, MemberNames.Mailid.toString(), mailid);
	}

	/**
	 * @return value of EmployeeID
	 */
	public final java.lang.String getEmployeeID()
	{
		return getEmployeeID(getContext());
	}

	/**
	 * @param context
	 * @return value of EmployeeID
	 */
	public final java.lang.String getEmployeeID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmployeeID.toString());
	}

	/**
	 * Set value of EmployeeID
	 * @param employeeid
	 */
	public final void setEmployeeID(java.lang.String employeeid)
	{
		setEmployeeID(getContext(), employeeid);
	}

	/**
	 * Set value of EmployeeID
	 * @param context
	 * @param employeeid
	 */
	public final void setEmployeeID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String employeeid)
	{
		getMendixObject().setValue(context, MemberNames.EmployeeID.toString(), employeeid);
	}

	/**
	 * @return value of Address
	 */
	public final java.lang.String getAddress()
	{
		return getAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of Address
	 */
	public final java.lang.String getAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Address.toString());
	}

	/**
	 * Set value of Address
	 * @param address
	 */
	public final void setAddress(java.lang.String address)
	{
		setAddress(getContext(), address);
	}

	/**
	 * Set value of Address
	 * @param context
	 * @param address
	 */
	public final void setAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address)
	{
		getMendixObject().setValue(context, MemberNames.Address.toString(), address);
	}

	/**
	 * Get value of Designation
	 * @param designation
	 */
	public final myfirstmodule.proxies.ENUM_Designation getDesignation()
	{
		return getDesignation(getContext());
	}

	/**
	 * @param context
	 * @return value of Designation
	 */
	public final myfirstmodule.proxies.ENUM_Designation getDesignation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Designation.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.ENUM_Designation.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Designation
	 * @param designation
	 */
	public final void setDesignation(myfirstmodule.proxies.ENUM_Designation designation)
	{
		setDesignation(getContext(), designation);
	}

	/**
	 * Set value of Designation
	 * @param context
	 * @param designation
	 */
	public final void setDesignation(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.ENUM_Designation designation)
	{
		if (designation != null) {
			getMendixObject().setValue(context, MemberNames.Designation.toString(), designation.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Designation.toString(), null);
		}
	}

	/**
	 * Get value of Status
	 * @param status
	 */
	public final myfirstmodule.proxies.ENUM_Status getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final myfirstmodule.proxies.ENUM_Status getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.ENUM_Status.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(myfirstmodule.proxies.ENUM_Status status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.ENUM_Status status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.EmcureUser that = (myfirstmodule.proxies.EmcureUser) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
